application: surlyfritter-hrd
version: 4
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /apple-touch-icon.png
  static_files: static/images/july4th.png
  upload: static/images/july4th.png

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /player
  static_files: static/player.html
  upload: static/player.html

- url: /reindeer
  static_files: static/better_than_reindeer.mp3
  upload: static/better_than_reindeer.mp3

- url: /movie
  static_files: static/movie.html
  upload: static/movie.html

- url: /resume
  static_files: static/resume.html
  upload: static/resume.html

- url: /resist
  static_files: static/resist.html
  upload: static/resist.html

- url: /flashcards
  script: flashcards.py

- url: /_ah/mail/.+ 
  script: Display.py 
  login: admin

- url: /.*
  script: Display.py

inbound_services:
- mail

builtins:
- remote_api: on
- appstats: on
